apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: i51koc2ji-python
  janus-idp.io/tekton: i51koc2ji-python
  backstage.io/kubernetes-id: i51koc2ji-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i51koc2ji-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
